{
 "title": "Taller 1 - Vision general",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Instancias vivas (up=1)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Total de peticiones (todos los servicios)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Peticiones por segundo (por servicio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_total[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tasa de error 5xx (por servicio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_total{status=~\"5..\"}[2m])) / sum by (job) (rate(http_requests_total[2m]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}